import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "ntienmanh94",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Manh",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Iphone 3",
      category: "mobile",
      image: "/images/img-product.jpg",
      price: 120,
      countInStock: 10,
      brand: "Iphone",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Samsung",
      category: "mobile",
      image: "/images/img-product.jpg",
      price: 100,
      countInStock: 20,
      brand: "Samsung",
      rating: 4.0,
      numReviews: 10,
      description: "low quality product",
    },
    {
      name: "Tablet",
      category: "tablet",
      image: "/images/img-product.jpg",
      price: 220,
      countInStock: 15,
      brand: "Iphone",
      rating: 4.8,
      numReviews: 17,
      description: "medium quality product",
    },
    {
      name: "Motorola",
      category: "mobile",
      image: "/images/img-product.jpg",
      price: 78,
      countInStock: 15,
      brand: "Motorola",
      rating: 4.5,
      numReviews: 14,
      description: "very low quality product",
    },
    {
      name: "Viewsonic2479",
      category: "screen",
      image: "/images/img-product.jpg",
      price: 65,
      countInStock: 5,
      brand: "Viewsonic",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Cloudfoam",
      category: "Shoes",
      image: "/images/img-product.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Adidas Stant smith",
      category: "Shoes",
      image: "/images/img-product.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "ADLV cute kids",
      category: "Shirt",
      image: "/images/img-product.jpg",
      price: 139,
      countInStock: 12,
      brand: "ADLV",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
